# Generated by Django 4.1 on 2022-09-20 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busyness',
            old_name='is_daleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='is_daleted',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='vakancys',
            name='tasks',
        ),
        migrations.AddField(
            model_name='tasks',
            name='vak',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vacancys.vakancys', verbose_name='Вакансия'),
        ),
    ]
