# Generated by Django 4.1 on 2022-09-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0002_rename_is_daleted_busyness_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakancys',
            name='salary',
            field=models.CharField(blank=True, default='з/п не указана', max_length=100, verbose_name='Заработная плата'),
        ),
    ]
