# Generated by Django 4.1 on 2022-09-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0003_alter_vakancys_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakancys',
            name='count',
            field=models.CharField(default='0', max_length=5, verbose_name='Количество просмотров'),
        ),
    ]
