# Generated by Django 4.1 on 2022-09-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0004_alter_vakancys_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='vak',
            new_name='vakancys',
        ),
    ]
