# Generated by Django 4.1 on 2022-09-20 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0005_rename_vak_tasks_vakancys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='vakancys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancys.vakancys', verbose_name='Вакансия'),
        ),
    ]
