# Generated by Django 4.1 on 2022-09-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0006_alter_tasks_vakancys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakancys',
            name='count',
            field=models.CharField(default='0', max_length=10, verbose_name='Количество просмотров'),
        ),
    ]
