# Generated by Django 4.1 on 2022-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0009_remove_vakancys_profile_vakancys_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakancys',
            name='vakancy_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название вакансии'),
        ),
    ]
