# Generated by Django 4.1 on 2022-10-02 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancys', '0011_remove_vakancys_user_vakancys_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vakancys',
            name='profile',
        ),
        migrations.AddField(
            model_name='vakancys',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Компания'),
        ),
    ]
