# Generated by Django 4.1 on 2022-10-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_name'),
        ('vacancys', '0012_remove_vakancys_profile_vakancys_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vakancys',
            name='user',
        ),
        migrations.AddField(
            model_name='vakancys',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Компания'),
        ),
    ]
