# Generated by Django 4.1 on 2022-10-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0015_vakancys_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vakancys',
            name='user',
        ),
    ]
