# Generated by Django 4.1 on 2022-10-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_name'),
        ('vacancys', '0016_remove_vakancys_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsVakancys',
            fields=[
                ('skills_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.skills')),
                ('skills_vak_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Скилл')),
            ],
            bases=('users.skills',),
        ),
        migrations.AddField(
            model_name='vakancys',
            name='skills',
            field=models.ManyToManyField(related_name='skillsvakancys', to='vacancys.skillsvakancys', verbose_name='Скиллы'),
        ),
    ]
