# Generated by Django 4.1 on 2022-10-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_name'),
        ('vacancys', '0017_skillsvakancys_vakancys_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakancys',
            name='skills',
            field=models.ManyToManyField(to='users.skills', verbose_name='Скиллы'),
        ),
        migrations.DeleteModel(
            name='SkillsVakancys',
        ),
    ]
