# Generated by Django 4.1 on 2022-10-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0018_alter_vakancys_skills_delete_skillsvakancys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vakancys',
            name='skills',
        ),
    ]
