# Generated by Django 4.1 on 2022-10-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0020_vakancys_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vakancys',
            old_name='meta',
            new_name='skills',
        ),
    ]
