# Generated by Django 4.1 on 2022-10-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0021_rename_meta_vakancys_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakancys',
            name='tasks',
            field=models.TextField(default=' ', max_length=3000, verbose_name='Описание задачи'),
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
