# Generated by Django 4.1 on 2022-09-19 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('image', models.ImageField(blank=True, default='profile_project/default.jpg', null=True, upload_to='profile_project', verbose_name='Фото проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('demo_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Демо-ссылка')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
