# Generated by Django 4.1 on 2022-09-19 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Скилл')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание скилла')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Скилл',
                'verbose_name_plural': 'Скиллы',
            },
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип пользователя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание типа пользователя')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'типы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Программист/компания')),
                ('tel', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
                ('adr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('biog', models.TextField(blank=True, null=True, verbose_name='Биография пользователя')),
                ('image', models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images', verbose_name='Аватар')),
                ('github', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на githab')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на twitter')),
                ('youtube', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на youtube')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на сайт')),
                ('id_type_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeuser_profile', to='users.typeuser', verbose_name='Тип пользователя')),
                ('skills', models.ManyToManyField(related_name='skills', to='users.skills', verbose_name='Скиллы')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
