# Generated by Django 4.1 on 2022-09-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skills_typeuser_alter_profile_options_profile_adr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=16, verbose_name='Телефон'),
        ),
    ]
