# Generated by Django 4.1 on 2022-09-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0004_profile_profile_name_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(related_name='project', to='projects.project', verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Программист/компания'),
        ),
    ]
