# Generated by Django 4.1 on 2022-09-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_date_add_profile_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_deleted',
        ),
    ]
