# Generated by Django 4.1 on 2022-10-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_profile_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_msg', models.CharField(blank=True, max_length=250, null=True, verbose_name='название сообщения')),
                ('body', models.TextField(verbose_name='сообщение')),
                ('is_read', models.BooleanField(default=False, null=True, verbose_name='статус сообщения')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='дата/время создания')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg2', to='users.profile', verbose_name='Получатель')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='users.profile', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['is_read', '-date_add'],
            },
        ),
    ]
