# Generated by Django 4.1 on 2022-10-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0009_alter_msg_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='name_msg',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тема'),
        ),
    ]
