# Generated by Django 4.1 on 2022-11-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0010_alter_msg_name_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='name_msg',
            field=models.CharField(default=False, max_length=250, verbose_name='Тема'),
        ),
    ]
